on:
  pull_request:
  push:
    branches:
      - mempool


name: Compile Check and Lint

jobs:
  check:
    name: Compile Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: './.github/actions/ci-rust-setup'
        with:
          cache-name: dev
      - run: cargo check --all-features

  fmt:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: './.github/actions/ci-rust-setup'
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: './.github/actions/ci-rust-setup'
        with:
          cache-name: test
      - run: cargo test --lib --all-features

  clippy:
    name: Linter
    runs-on: ubuntu-latest
    needs: [check]
    strategy:
      matrix: # Try all combinations of features. Some times weird things appear.
        features: [
          '',
          '-F electrum-discovery',
          '-F liquid',
          '-F electrum-discovery,liquid',
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: './.github/actions/ci-rust-setup'
        with:
          cache-name: dev
          components: clippy
      - name: Clippy with Features = ${{ matrix.features }}
        run: cargo clippy ${{ matrix.features }} -- -D warnings
